local test = require("santoku.test")
local profile = require("santoku.profile")
local num = require("santoku.num")
local str = require("santoku.string")
local utc = require("santoku.utc")

local function burn (secs)
  local t0 = utc.time(true)
  while utc.time(true) - t0 < secs do end
end

local function byl ()
  local r = profile.report()
  local m = {}
  for i = 1, #r do
    m[r[i].label] = r[i]
  end
  return m
end

test("disabled calls pass every value through and record nothing", function ()
  profile.disable()
  profile.reset()
  assert(profile.enabled() == false)
  local function f (a, b, ...)
    return a + b, ...
  end
  local w = profile.wrapped("off.wrapped", f)
  local x, y, z = w(1, 2, "y", "z")
  assert(x == 3 and y == "y" and z == "z")
  local p, q = profile.timed("off.timed", f, 1, 2, "q")
  assert(p == 3 and q == "q")
  local fin = profile.span("off.span")
  fin()
  assert(#profile.report() == 0)
end)

test("disabled spans share one finisher and allocate nothing", function ()
  profile.disable()
  assert(profile.span("off.a") == profile.span("off.b"))
  local function f (a, b)
    return a + b
  end
  local w = profile.wrapped("off.noalloc", f)
  assert(w(1, 2) == 3)
  collectgarbage()
  collectgarbage()
  local before = collectgarbage("count")
  for i = 1, 100000 do
    w(i, 1)
  end
  local after = collectgarbage("count")
  assert(after <= before, after - before)
end)

test("nested spans report self exclusive of instrumented children", function ()
  profile.reset()
  profile.enable()
  local inner = profile.wrapped("inner", function ()
    burn(0.02)
  end)
  local outer = profile.wrapped("outer", function ()
    burn(0.01)
    inner()
    inner()
  end)
  outer()
  profile.disable()
  local m = byl()
  assert(m.outer.calls == 1)
  assert(m.inner.calls == 2)
  assert(m.inner.self == m.inner.total)
  assert(m.outer.total > m.inner.total)
  assert(m.outer.self < m.outer.total)
  assert(num.abs(m.outer.self - (m.outer.total - m.inner.total)) < 0.005)
  assert(m.inner.min <= m.inner.mean and m.inner.mean <= m.inner.max)
  assert(m.outer.open == 0 and m.outer.unwound == 0)
  local r = profile.report()
  assert(r[1].self >= r[2].self)
end)

test("recursion pops by frame, not by name", function ()
  profile.reset()
  profile.enable()
  local rec
  rec = profile.wrapped("rec", function (n)
    burn(0.005)
    if n > 1 then
      rec(n - 1)
    end
  end)
  rec(3)
  profile.disable()
  local m = byl()
  assert(m.rec.calls == 3)
  assert(m.rec.open == 0)
  assert(m.rec.unwound == 0)
  assert(m.rec.self < m.rec.total)
  assert(num.abs(m.rec.self - m.rec.max) < 0.005)
end)

test("timed and span nest together", function ()
  profile.reset()
  profile.enable()
  local fin = profile.span("block")
  profile.timed("step", burn, 0.02)
  burn(0.01)
  fin()
  profile.disable()
  local m = byl()
  assert(m.block.calls == 1 and m.step.calls == 1)
  assert(m.block.total > m.step.total)
  assert(num.abs(m.block.self - (m.block.total - m.step.total)) < 0.005)
end)

test("spans interleave across coroutines without crossing stacks", function ()
  profile.reset()
  profile.enable()
  local a = coroutine.create(function ()
    local fin = profile.span("co.a")
    burn(0.01)
    coroutine.yield()
    burn(0.01)
    fin()
  end)
  local b = coroutine.create(function ()
    local fin = profile.span("co.b")
    profile.timed("co.b.child", burn, 0.01)
    coroutine.yield()
    burn(0.01)
    fin()
  end)
  local fin = profile.span("co.main")
  assert(coroutine.resume(a))
  assert(coroutine.resume(b))
  assert(coroutine.resume(a))
  assert(coroutine.resume(b))
  fin()
  profile.disable()
  local m = byl()
  assert(m["co.a"].calls == 1 and m["co.b"].calls == 1)
  assert(m["co.a"].open == 0 and m["co.b"].open == 0)
  assert(m["co.a"].unwound == 0 and m["co.b"].unwound == 0)
  assert(m["co.a"].self == m["co.a"].total)
  assert(m["co.b"].self < m["co.b"].total)
  assert(num.abs(m["co.b"].self - (m["co.b"].total - m["co.b.child"].total)) < 0.005)
  assert(m["co.main"].self == m["co.main"].total)
  assert(m["co.main"].total > m["co.a"].total)
  assert(m["co.a"].total > 0.02)
end)

test("a span abandoned with its coroutine stays open and is never counted", function ()
  profile.reset()
  profile.enable()
  local co = coroutine.create(function ()
    local fin = profile.span("abandoned")
    coroutine.yield()
    fin()
  end)
  assert(coroutine.resume(co))
  co = nil -- luacheck: ignore
  collectgarbage()
  collectgarbage()
  profile.disable()
  local m = byl()
  assert(m.abandoned.calls == 0)
  assert(m.abandoned.open == 1)
  assert(m.abandoned.total == 0)
end)

test("an error through a span unwinds the frames above it", function ()
  profile.reset()
  profile.enable()
  local boom = profile.wrapped("boom", function ()
    error("boom")
  end)
  local outer = profile.wrapped("outer.unwind", function ()
    pcall(boom)
    burn(0.01)
  end)
  outer()
  profile.disable()
  local m = byl()
  assert(m.boom.calls == 0)
  assert(m.boom.unwound == 1)
  assert(m.boom.open == 0)
  assert(m.boom.total == 0)
  assert(m["outer.unwind"].open == 0)
  assert(m["outer.unwind"].unwound == 0)
  assert(m["outer.unwind"].calls == 1)
  assert(m["outer.unwind"].self == m["outer.unwind"].total)
  assert(m["outer.unwind"].total > 0.005)
end)

test("wrap instruments named fields in place", function ()
  profile.reset()
  profile.enable()
  local M = {
    add = function (a, b)
      return a + b
    end,
    all = function (...)
      return ...
    end,
  }
  M.get = function (self, k)
    return self[k]
  end
  profile.wrap(M, { "add", "all" }, "M.")
  profile.wrap(M, "get")
  assert(M.add(1, 2) == 3)
  local a, b, c = M.all(1, nil, 3)
  assert(a == 1 and b == nil and c == 3)
  assert(M:get("add") ~= nil)
  profile.disable()
  local m = byl()
  assert(m["M.add"].calls == 1)
  assert(m["M.all"].calls == 1)
  assert(m.get.calls == 1)
  local s = profile.format()
  assert(str.find(s, "M.add", 1, true))
  assert(str.find(s, "label", 1, true))
  assert(str.find(s, "elapsed", 1, true))
  assert(profile.elapsed() >= 0)
end)

test("reset zeroes counters and keeps labels stable", function ()
  profile.reset()
  profile.enable()
  local f = profile.wrapped("resettable", burn)
  f(0.005)
  assert(byl().resettable.calls == 1)
  profile.reset()
  assert(byl().resettable == nil)
  f(0.005)
  assert(byl().resettable.calls == 1)
  profile.disable()
  profile.reset()
end)

